name: MCP Architecture Agent

on:
  workflow_dispatch:
    inputs:
      objective:
        description: High-level objective or feature request for planning
        required: true
      context:
        description: Links, notes, or file pointers with additional background
        required: false
        default: ''
      constraints:
        description: Performance, compatibility, or release constraints
        required: false
        default: ''
      roadmap:
        description: Relevant roadmap items or discussions to factor into the plan
        required: false
        default: ''
      post_as_comment:
        description: Issue/PR number to post the plan as a comment (optional)
        required: false
        default: ''

jobs:
  generate-plan:
    name: Generate architecture brief
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      models: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run architecture planning prompt
        id: planner
        uses: actions/ai-inference@v1
        with:
          prompt-file: .github/mcp-architecture.prompt.yml
          input: |
            objective: ${{ github.event.inputs.objective }}
            context: ${{ github.event.inputs.context }}
            constraints: ${{ github.event.inputs.constraints }}
            roadmap: ${{ github.event.inputs.roadmap }}

      - name: Capture output in job summary
        run: |
          cat <<'EOF' >> "$GITHUB_STEP_SUMMARY"
          ${{ steps.planner.outputs.response }}
          EOF

      - name: Optionally post comment
        if: ${{ github.event.inputs.post_as_comment != '' && steps.planner.outputs.response != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## 🧭 MCP Architecture Plan\n\n${process.env.RESPONSE}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(process.env.ISSUE_NUMBER),
              body,
            });
        env:
          RESPONSE: ${{ steps.planner.outputs.response }}
          ISSUE_NUMBER: ${{ github.event.inputs.post_as_comment }}
